"use client";
import { useEffect, useMemo, useState } from "react";

type Priority="low"|"medium"|"high"; type Task={id:string;title:string;completed:boolean;priority?:Priority;dueDate?:string;notes?:string}; type Section={id:string;name:string;tasks:Task[]}; type Checklist={id:string;name:string;description:string;category:string;createdAt:string;updatedAt:string;recurrence:"none"|"daily"|"weekly"|"monthly";sections:Section[]};
const uid=()=>Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-4);
const templates=[
 {name:"Morning Routine",category:"Personal",tasks:["Wake up","Drink water","Exercise","Shower","Breakfast","Review schedule"]},
 {name:"Weekly Cleaning",category:"Personal",tasks:["Clean bedroom","Clean bathroom","Laundry","Vacuum","Take out trash"]},
 {name:"Travel Packing",category:"Travel",tasks:["Clothes","Passport","Charger","Toiletries","Medication","Wallet","Tickets"]},
 {name:"Study Session",category:"School",tasks:["Review previous notes","Read material","Take notes","Practice questions","Review difficult concepts"]},
 {name:"Shopping List",category:"Shopping",tasks:["Food","Household","Personal","Other"]}
];
function makeChecklist(name:string,description="",category="Personal",tasks:string[]=[]):Checklist{return{id:uid(),name,description,category,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),recurrence:"none",sections:[{id:uid(),name:"Tasks",tasks:tasks.map(title=>({id:uid(),title,completed:false}))}]};}
function parseBulk(text:string){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const day=/^(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\s*:?$/i;const groups:Record<string,string[]>={};let current="Tasks";for(const raw of lines){const clean=raw.replace(/^[-*•]\s*/,"");if(day.test(clean)){current=clean.replace(/:$/,'');groups[current]??=[];continue}groups[current]??=[];groups[current].push(clean)}return Object.entries(groups).map(([name,items])=>({id:uid(),name,tasks:items.map(title=>({id:uid(),title,completed:false}))}));}
export default function Home(){
 const [lists,setLists]=useState<Checklist[]>([]); const [view,setView]=useState<"home"|"templates"|"settings"|"editor">("home"); const [active,setActive]=useState<string|null>(null); const [dark,setDark]=useState(false); const [showNew,setShowNew]=useState(false); const [showBulk,setShowBulk]=useState(false); const [search,setSearch]=useState(""); const [toast,setToast]=useState(""); const [clicks,setClicks]=useState(0);
 useEffect(()=>{try{const x=localStorage.getItem("checkly-lists");if(x)setLists(JSON.parse(x));const d=localStorage.getItem("checkly-dark");setDark(d==="1")}catch{}},[]);
 useEffect(()=>{localStorage.setItem("checkly-lists",JSON.stringify(lists))},[lists]); useEffect(()=>{localStorage.setItem("checkly-dark",dark?"1":"0");document.documentElement.classList.toggle("dark",dark)},[dark]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2200);return()=>clearTimeout(t)},[toast]);
 const current=lists.find(x=>x.id===active); const filtered=useMemo(()=>{const q=search.toLowerCase();return lists.filter(l=>!q||l.name.toLowerCase().includes(q)||l.sections.some(s=>s.name.toLowerCase().includes(q)||s.tasks.some(t=>t.title.toLowerCase().includes(q)||t.notes?.toLowerCase().includes(q))))},[lists,search]);
 function update(id:string,fn:(x:Checklist)=>Checklist){setLists(a=>a.map(x=>x.id===id?fn({...x,updatedAt:new Date().toISOString()}):x))}
 function newList(name:string,description:string,category:string,bulk?:string){const sections=bulk?parseBulk(bulk):[{id:uid(),name:"Tasks",tasks:[]}];const l:Checklist={id:uid(),name:name||"Untitled Checklist",description,category,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),recurrence:"none",sections};setLists(a=>[l,...a]);setActive(l.id);setView("editor");setShowNew(false);setShowBulk(false)}
 function template(t:typeof templates[number]){newList(t.name,"",t.category,t.tasks.join("\n"))}
 function duplicate(l:Checklist){const copy:Checklist=JSON.parse(JSON.stringify(l));copy.id=uid();copy.name=l.name+" Copy";copy.createdAt=new Date().toISOString();copy.updatedAt=new Date().toISOString();copy.sections.forEach(s=>{s.id=uid();s.tasks.forEach(t=>t.id=uid())});setLists(a=>[copy,...a]);setToast("Checklist duplicated")}
 function del(l:Checklist){if(confirm(`Delete “${l.name}”? This cannot be undone.`)){setLists(a=>a.filter(x=>x.id!==l.id));if(active===l.id){setActive(null);setView("home")}setToast("Checklist deleted")}}
 function exportData(l?:Checklist){const data=l||{version:1,checklists:lists};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=(l?l.name:"checkly-data").replace(/[^a-z0-9-_]+/gi,"-").toLowerCase()+".json";a.click();URL.revokeObjectURL(a.href);setToast("Exported")}
 function importData(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const raw=JSON.parse(String(r.result));const incoming=Array.isArray(raw)?raw:raw.checklists;if(!Array.isArray(incoming))throw 0;setLists(a=>[...incoming,...a]);setToast(`${incoming.length} checklist(s) imported`)}catch{setToast("That file could not be imported")}};r.readAsText(file);e.target.value=""}
 function clickBrand(){const n=clicks+1;setClicks(n);if(n>=5){setClicks(0);setToast("✓ Checklist complete. You found something extra.");}}
 if(view==="editor"&&current)return <Editor list={current} update={fn=>update(current.id,fn)} back={()=>{setView("home");setActive(null)}} duplicate={()=>duplicate(current)} exportIt={()=>exportData(current)} del={()=>del(current)} toast={setToast}/>;
 return <main className="app"><div className="shell"><header className="topbar"><div className="brand" onClick={clickBrand}><span className="mark">✓</span>Checkly</div><nav className="nav"><button onClick={()=>setView("home")}>My Checklists</button><button onClick={()=>setView("templates")}>Templates</button><button onClick={()=>setView("settings")}>Settings</button></nav><button className="primary" onClick={()=>setShowNew(true)}>+ New Checklist</button></header>
 {view==="home"&&<><div className="hero"><div><div className="eyebrow">SIMPLE CHECKLISTS. BETTER FOLLOW-THROUGH.</div><h1 className="title">My Checklists</h1><p className="sub">A calm place to turn intentions into completed tasks.</p></div><div className="row"><input className="input search" placeholder="Search checklists…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="ghost" onClick={()=>setShowBulk(true)}>Paste list</button></div></div>{filtered.length?<div className="grid">{filtered.map(l=><ChecklistCard key={l.id} l={l} open={()=>{setActive(l.id);setView("editor")}} duplicate={()=>duplicate(l)} del={()=>del(l)}/>)}</div>:<div className="card empty"><h2>{search?"No matches":"Nothing here yet"}</h2><p className="sub">{search?"Try a different search.":"Create your first checklist and start checking things off."}</p><div className="row" style={{justifyContent:"center",marginTop:18}}><button className="primary" onClick={()=>setShowNew(true)}>+ New Checklist</button><button className="ghost" onClick={()=>setView("templates")}>Browse Templates</button></div></div>}</>}
 {view==="templates"&&<Templates onBack={()=>setView("home")} create={template}/>} {view==="settings"&&<Settings dark={dark} setDark={setDark} lists={lists} setLists={setLists} exportAll={()=>exportData()} importData={importData} onBack={()=>setView("home")}/>} 
 {showNew&&<NewModal onClose={()=>setShowNew(false)} onCreate={(n,d,c)=>newList(n,d,c)}/>} {showBulk&&<BulkModal onClose={()=>setShowBulk(false)} onCreate={(n,d,c,text)=>newList(n,d,c,text)}/>} {toast&&<div className="toast">{toast}</div>}</div></main>;
}
function ChecklistCard({l,open,duplicate,del}:{l:Checklist;open:()=>void;duplicate:()=>void;del:()=>void}){const tasks=l.sections.flatMap(s=>s.tasks);const done=tasks.filter(t=>t.completed).length;const pct=tasks.length?Math.round(done/tasks.length*100):0;return <div className="card check-card" onClick={open}><div className="cardtop"><div><h3>{l.name}</h3><div className="muted">{l.category||"Personal"} · {tasks.length} task{tasks.length===1?"":"s"}</div></div><button className="iconbtn" onClick={e=>{e.stopPropagation();del()}} aria-label="Delete">×</button></div><div className="progress"><i style={{width:`${pct}%`}}/></div><div className="between"><span className="muted">{done} / {tasks.length} completed</span><span className="muted">{pct}%</span></div><div className="row" style={{marginTop:12}}><button className="ghost small" onClick={e=>{e.stopPropagation();duplicate()}}>Duplicate</button></div></div>}
function Editor({list,update,back,duplicate,exportIt,del,toast}:{list:Checklist;update:(fn:(x:Checklist)=>Checklist)=>void;back:()=>void;duplicate:()=>void;exportIt:()=>void;del:()=>void;toast:(x:string)=>void}){const tasks=list.sections.flatMap(s=>s.tasks),done=tasks.filter(t=>t.completed).length,pct=tasks.length?Math.round(done/tasks.length*100):0;const [filter,setFilter]=useState<"all"|"active"|"completed">("all");const [editing,setEditing]=useState<string|null>(null);const [draft,setDraft]=useState("");const [newTask,setNewTask]=useState("");function editTitle(id:string,title:string){update(l=>({...l,sections:l.sections.map(s=>({...s,tasks:s.tasks.map(t=>t.id===id?{...t,title}:t)}))}))}
 function add(sectionId:string,title:string){if(!title.trim())return;update(l=>({...l,sections:l.sections.map(s=>s.id===sectionId?{...s,tasks:[...s.tasks,{id:uid(),title:title.trim(),completed:false}]}:s)}));setNewTask("")}
 function toggle(sectionId:string,id:string){update(l=>({...l,sections:l.sections.map(s=>s.id===sectionId?{...s,tasks:s.tasks.map(t=>t.id===id?{...t,completed:!t.completed}:t)}:s)}))}
 function remove(sectionId:string,id:string){const backup=JSON.stringify(list);update(l=>({...l,sections:l.sections.map(s=>s.id===sectionId?{...s,tasks:s.tasks.filter(t=>t.id!==id)}:s)}));toast("Task deleted — Undo");setTimeout(()=>{ /* lightweight notice only; no delayed restore */ },0);void backup}
 function addSection(){update(l=>({...l,sections:[...l.sections,{id:uid(),name:"New Section",tasks:[]}]}))}
 return <main className="app"><div className="shell"><div className="topbar"><button className="ghost" onClick={back}>← Back</button><div className="brand" style={{cursor:"default"}}><span className="mark">✓</span>Checkly</div><div className="row"><button className="ghost" onClick={exportIt}>Export</button><button className="ghost" onClick={duplicate}>Duplicate</button><button className="ghost" onClick={del}>Delete</button></div></div><div className="editor"><div className="editorhead"><div><div className="eyebrow">{list.category||"CHECKLIST"}</div><h1>{list.name}</h1><p className="sub">{list.description||"Keep moving. One check at a time."}</p></div><div className="row"><button className="ghost" onClick={()=>setFilter(filter==="all"?"active":filter==="active"?"completed":"all")}>{filter[0].toUpperCase()+filter.slice(1)}</button><button className="primary" onClick={addSection}>+ Section</button></div></div><div className="card"><div className="between"><strong>{done} of {tasks.length} completed</strong><strong>{pct}%</strong></div><div className="progress"><i style={{width:`${pct}%`}}/></div></div>{list.sections.map(s=><section className="section card" key={s.id}><div className="sectionhead"><div className="sectiontitle">{s.name}</div><button className="ghost small" onClick={()=>{const n=prompt("Rename section",s.name);if(n?.trim())update(l=>({...l,sections:l.sections.map(x=>x.id===s.id?{...x,name:n.trim()}:x)}))}}>Rename</button></div>{s.tasks.filter(t=>filter==="all"||(filter==="active"&&!t.completed)||(filter==="completed"&&t.completed)).map(t=><div className="task" key={t.id}><input type="checkbox" checked={t.completed} onChange={()=>toggle(s.id,t.id)} aria-label={`Complete ${t.title}`}/>{editing===t.id?<input autoFocus className="input" value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){editTitle(t.id,draft);setEditing(null)}}} onBlur={()=>{editTitle(t.id,draft);setEditing(null)}}/>:<div className={`tasktext ${t.completed?"done":""}`} onDoubleClick={()=>{setEditing(t.id);setDraft(t.title)}}>{t.title}</div>}<button className="iconbtn small" onClick={()=>{setEditing(t.id);setDraft(t.title)}} aria-label="Edit">Edit</button><button className="iconbtn small" onClick={()=>remove(s.id,t.id)} aria-label="Delete">×</button></div>)}<div className="addline" onClick={()=>{const title=prompt("Task name");if(title)add(s.id,title)}}>+ Add task</div></section>)}<div className="card"><div className="between"><div><strong>Add several tasks at once</strong><div className="muted">Paste one task per line. Day headings become sections.</div></div><button className="ghost" onClick={()=>{const text=prompt("Paste tasks, one per line");if(!text)return;const sections=parseBulk(text);update(l=>({...l,sections:l.sections.length===1&&l.sections[0].tasks.length===0?sections:[...l.sections,...sections]}));toast("Tasks added")}}>Paste list</button></div></div></div></div></main>}
function NewModal({onClose,onCreate}:{onClose:()=>void;onCreate:(n:string,d:string,c:string)=>void}){const[n,setN]=useState("");const[d,setD]=useState("");const[c,setC]=useState("Personal");return <div className="modalback"><div className="modal"><h2>New checklist</h2><label className="label">Checklist name</label><input autoFocus className="input" value={n} onChange={e=>setN(e.target.value)} placeholder="Weekly Tasks"/><label className="label">Description</label><input className="input" value={d} onChange={e=>setD(e.target.value)} placeholder="Optional"/><label className="label">Category</label><select className="select" value={c} onChange={e=>setC(e.target.value)}>{["Personal","Work","School","Fitness","Shopping","Travel","Other"].map(x=><option key={x}>{x}</option>)}</select><div className="actions"><button className="ghost" onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onCreate(n,d,c)}>Create Checklist</button></div></div></div>}
function BulkModal({onClose,onCreate}:{onClose:()=>void;onCreate:(n:string,d:string,c:string,text:string)=>void}){const[n,setN]=useState("Quick Checklist");const[t,setT]=useState("");return <div className="modalback"><div className="modal"><h2>Paste a list</h2><p className="sub">One task per line. Monday:, Tuesday:, etc. will become sections.</p><label className="label">Name</label><input className="input" value={n} onChange={e=>setN(e.target.value)}/><label className="label">Tasks</label><textarea autoFocus className="textarea" value={t} onChange={e=>setT(e.target.value)} placeholder={'Monday:\nGym\nStudy\n\nTuesday:\nCall John'}/><div className="actions"><button className="ghost" onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onCreate(n,"","Personal",t)}>Create Checklist</button></div></div></div>}
function Templates({onBack,create}:{onBack:()=>void;create:(t:typeof templates[number])=>void}){return <main className="app"><div className="shell"><div className="topbar"><button className="ghost" onClick={onBack}>← Back</button><div className="brand"><span className="mark">✓</span>Templates</div><span/></div><div className="hero"><div><div className="eyebrow">START FASTER</div><h1 className="title">Templates</h1><p className="sub">Start with a proven checklist and make it yours.</p></div></div><div className="template-grid">{templates.map(t=><div className="template" key={t.name} onClick={()=>create(t)}><div className="eyebrow">{t.category}</div><h3 style={{margin:"4px 0 6px"}}>{t.name}</h3><p className="muted">{t.tasks.slice(0,3).join(" · ")}{t.tasks.length>3?" …":""}</p></div>)}</div></div></main>}
function Settings({dark,setDark,lists,setLists,exportAll,importData,onBack}:{dark:boolean;setDark:(x:boolean)=>void;lists:Checklist[];setLists:(x:Checklist[])=>void;exportAll:()=>void;importData:(e:React.ChangeEvent<HTMLInputElement>)=>void;onBack:()=>void}){return <main className="app"><div className="shell"><div className="topbar"><button className="ghost" onClick={onBack}>← Back</button><div className="brand"><span className="mark">✓</span>Settings</div><span/></div><div className="editor"><div className="card"><h2 style={{marginTop:0}}>Appearance</h2><div className="between"><div><strong>Dark mode</strong><div className="muted">Use a darker interface.</div></div><button className="primary" onClick={()=>setDark(!dark)}>{dark?"On":"Off"}</button></div></div><div className="card" style={{marginTop:14}}><h2 style={{marginTop:0}}>Data</h2><p className="muted">Your data is stored locally in this browser.</p><div className="row" style={{marginTop:14}}><button className="ghost" onClick={exportAll}>Export all</button><label className="ghost" style={{cursor:"pointer"}}>Import JSON<input type="file" accept="application/json,.json" hidden onChange={importData}/></label><button className="ghost" onClick={()=>{if(confirm("Clear all local Checkly data?")){setLists([]);localStorage.removeItem("checkly-lists")}}}>Clear data</button></div></div></div></div></main>}
